### ISSUE TITLE
Image with optical corrections

### ISSUE THREAD

**Issue by Nevu** [simoncozens/GlyphsPlugins#1]
Hello,

I use this plugin and noticed the optical in-corrections in the image of "rotate".
Maybe you want to use my adjust image below.

Thx
![rotational](https://cloud.githubusercontent.com/assets/2456068/11495336/a9267de2-980a-11e5-926d-fef87c9b0350.png)

**Comment by simoncozens** [comment]
Thank you - I've committed this to the repository.
